insert into Libros values ("1","Java","Cecilio","editorial1");
insert into Libros values ("2","Nét","Pedro","editorial2");
insert into Libros values ("3","PHP","Cecilio","editorial3");
insert into Capitulos values ("introduccion",25,"1");
insert into Capitulos values ("basico",12,"1");
insert into Capitulos values ("intro",25,"2");
insert into Editoriales values ("editorial1","categoriaA");
insert into Editoriales values ("editorial2","categoriaB");
insert into Editoriales values ("editorial3","categoriaC");